// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__eUljtiKOG6kCHQOjSPekRwAstRdY7o',
    appId: '1:843462858965:web:9fb8dc2f8cd0fd9ad82a5c',
    messagingSenderId: '843462858965',
    projectId: 'flash-chat-48425',
    authDomain: 'flash-chat-48425.firebaseapp.com',
    storageBucket: 'flash-chat-48425.appspot.com',
    measurementId: 'G-K5RZ1R17HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-J3W2ZI7c0ZF_gdfW2KpAzjECl2i3z8',
    appId: '1:843462858965:android:ae3ec195322a3a31d82a5c',
    messagingSenderId: '843462858965',
    projectId: 'flash-chat-48425',
    storageBucket: 'flash-chat-48425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6zRAt2bSYmlh-9qFrELxo72gW5oen9Y',
    appId: '1:843462858965:ios:84d5c7d8de99a84cd82a5c',
    messagingSenderId: '843462858965',
    projectId: 'flash-chat-48425',
    storageBucket: 'flash-chat-48425.appspot.com',
    iosClientId: '843462858965-fj9d6ug0ju4j6aecojumdd2hq05nva24.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6zRAt2bSYmlh-9qFrELxo72gW5oen9Y',
    appId: '1:843462858965:ios:84d5c7d8de99a84cd82a5c',
    messagingSenderId: '843462858965',
    projectId: 'flash-chat-48425',
    storageBucket: 'flash-chat-48425.appspot.com',
    iosClientId: '843462858965-fj9d6ug0ju4j6aecojumdd2hq05nva24.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
